--- 
pool: 
  vmImage: ubuntu-latest
steps: 
  - 
    displayName: "Build an image"
    inputs: 
      Dockerfile: app/Dockerfile
      command: build
      repository: $(imageName)
    task: Docker@2
trigger: 
  - main
variables: 
  imageName: pipelines-javascript-docker