trigger:
- main

pool:
  vmImage: 'ubuntu-latest' # set to windows-latest or another Windows vmImage for Windows builds

steps:
- task: Docker@2
  displayName: Build an image
  inputs:
   repository: 
   command: build
   Dockerfile: app/Dockerfile

- task: aquasecScanner@4
  inputs:
      image: 'pipelines-javascript-docker'
      register: true
      hideBase: false
      showNegligible: false
      windowsScannerVersion: '6.5.0'
      scanner: 'registry.aquasec.com/scanner:2022.4'
      connection: 'Aqua Scanner'
      showWillNotFix: true'
