trigger:
- main

pool:
  vmImage: 'ubuntu-latest' # set to windows-latest or another Windows vmImage for Windows builds

variables:
  imageName: 'pipelines-javascript-docker'

steps:
- task: Docker@2
  displayName: Build an image
  inputs:
   repository: 
   command: build
   Dockerfile: app/Dockerfile

- task: aquasecScanner@4
  inputs:
    image: '$(imageName)'
    scanType: 'local'
    register: false
    hideBase: false
    showNegligible: false
    windowsScannerVersion: '6.5.0'
    connection: 'Aqua Scanner'

